"""ajout de la table projet

Revision ID: 7f3c9d4a69d0
Revises: e4183338eb0a
Create Date: 2025-09-07 16:26:46.256743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3c9d4a69d0'
down_revision = 'e4183338eb0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('img_url', sa.String(length=100), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projet')
    # ### end Alembic commands ###
