"""Ajout de la table Celebrity

Revision ID: a6b74dfb8f37
Revises: 7f3c9d4a69d0
Create Date: 2025-09-16 19:15:21.773716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b74dfb8f37'
down_revision = '7f3c9d4a69d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celebrity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('age', sa.String(length=3), nullable=True),
    sa.Column('profession', sa.String(length=150), nullable=True),
    sa.Column('taille', sa.String(length=10), nullable=True),
    sa.Column('Description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celebrity')
    # ### end Alembic commands ###
