"""modiciation of the Celebrity Class

Revision ID: ae94f8fbb920
Revises: a6b74dfb8f37
Create Date: 2025-09-20 17:46:33.500843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae94f8fbb920'
down_revision = 'a6b74dfb8f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands manualy created by me because SQLite do not support "ALTER" commands ###
    # Step 1: Create a new temporary table with the correct schema (NOT NULL)
    op.execute("""
        CREATE TABLE celebrite (
            id INTEGER PRIMARY KEY,
            nom VARCHAR(100) NOT NULL,
            prenom VARCHAR(100) NOT NULL,
            age SMALLINT,
            profession VARCHAR(500),
            taille NUMERIC(5, 2) NOT NULL,
            "Description" VARCHAR(550) NOT NULL
        )
    """)

    # Step 2: Copy the data from the old table to the new one
    op.execute("""
        INSERT INTO celebrite (id, nom, prenom, age, profession, taille, "Description")
        SELECT id, nom, prenom, age, profession, taille, "Description" FROM celebrity
    """)

    # Step 3: Drop the old table
    op.execute("DROP TABLE celebrity")

    # ### end of manual commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE celebrity (
            id INTEGER PRIMARY KEY,
            nom VARCHAR(100),
            prenom VARCHAR(100),
            age VARCHAR(3),
            profession VARCHAR(150),
            taille VARCHAR(10),
            "Description" VARCHAR(150) 
        )
    """)

    op.execute("""
        INSERT INTO celebrity (id, nom, prenom, age, profession, taille, "Description")
        SELECT id, nom, prenom, age, profession, taille, "Description" FROM celebrite
    """)

    op.execute("DROP TABLE celebrite")
    # ### end Alembic commands ###
