"""Adding the Table User

Revision ID: f67deaa70832
Revises: ae94f8fbb920
Create Date: 2025-09-20 19:58:29.157853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67deaa70832'
down_revision = 'ae94f8fbb920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celebrity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('profession', sa.String(length=500), nullable=True),
    sa.Column('taille', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('Description', sa.String(length=550), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('celebrite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celebrite',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('age', sa.SMALLINT(), nullable=True),
    sa.Column('profession', sa.VARCHAR(length=500), nullable=True),
    sa.Column('taille', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('Description', sa.VARCHAR(length=550), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('celebrity')
    # ### end Alembic commands ###
