"""Added a timezone-aware date to Article

Revision ID: e4183338eb0a
Revises: c3bd1687afc2
Create Date: 2025-09-07 16:20:24.463755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4183338eb0a'
down_revision = 'c3bd1687afc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'date')
    # ### end Alembic commands ###
