"""updating table Celebrity to have a relation with table User

Revision ID: eb21c2baf092
Revises: f67deaa70832
Create Date: 2025-09-24 22:22:24.874302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb21c2baf092'
down_revision = 'f67deaa70832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celebrity', sa.Column('user_id', sa.Integer()))
    op.create_foreign_key(None, 'celebrity', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'celebrity', type_='foreignkey')
    op.drop_column('celebrity', 'user_id')
    # ### end Alembic commands ###
